Write-Host "Barbera local bootstrap"
Write-Host "1. Install Go 1.26+ dan pastikan PATH mengarah ke go.exe"
Write-Host "2. Install pnpm: npm install -g pnpm"
Write-Host "3. Copy .env.example ke .env"
Write-Host "4. Siapkan PostgreSQL lokal atau container, lalu isi .env dengan DSN yang benar"
Write-Host "5. Install dependency frontend dengan pnpm install"
Write-Host "6. Jalankan go run ./cmd/migrate"
Write-Host "7. Jalankan go run ./cmd/seed"
Write-Host "8. Lihat docs/runbooks/local-testing.md untuk test flow"
